//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoIngreso
    {
        public int IdDocumentoIngreso { get; set; }
        public int IdIngreso { get; set; }
        public string NombreArchivoOriginal { get; set; }
        public string NombreArchivoFisico { get; set; }
        public string RutaArchivo { get; set; }
        public string ExtensionArchivo { get; set; }
        public string ContentType { get; set; }
        public Nullable<long> TamanioBytes { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    }
}
