//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        public int IdGasto { get; set; }
        public int IdUsuario { get; set; }
        public int IdCategoria { get; set; }
        public int IdModoPago { get; set; }
        public int IdDivisa { get; set; }
        public decimal MontoGasto { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaGasto { get; set; }
    }
}
