//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialGasto
    {
        public int IdHistorialGasto { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> Idcategoria { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> IdDivisa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaDeGuardado { get; set; }
        public string Descripcion { get; set; }
    }
}
