//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaAhorro
    {
        public int IdMetaAhorro { get; set; }
        public int IdUsuario { get; set; }
        public int IdDivisa { get; set; }
        public int IdEstadoMetaAhorro { get; set; }
        public string Nombre { get; set; }
        public decimal MontoObjetivo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaMeta { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<decimal> MontoGuardado { get; set; }
    }
}
