//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanzasDBEntities : DbContext
    {
        public FinanzasDBEntities()
            : base("name=FinanzasDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AhorroHistorial> AhorroHistorial { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Divisa> Divisa { get; set; }
        public virtual DbSet<DocumentoGasto> DocumentoGasto { get; set; }
        public virtual DbSet<DocumentoIngreso> DocumentoIngreso { get; set; }
        public virtual DbSet<EstadoMetaAhorro> EstadoMetaAhorro { get; set; }
        public virtual DbSet<Gasto> Gasto { get; set; }
        public virtual DbSet<HistorialGasto> HistorialGasto { get; set; }
        public virtual DbSet<HistorialIngreso> HistorialIngreso { get; set; }
        public virtual DbSet<Ingreso> Ingreso { get; set; }
        public virtual DbSet<MetaAhorro> MetaAhorro { get; set; }
        public virtual DbSet<ModoPago> ModoPago { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<TipoIngreso> TipoIngreso { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
